name: Build hsrp.tex

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Compile LaTeX (hsrp.tex)
        uses: xu-cheng/latex-action@v3
        with:
          root_file: hsrp.tex

      - name: Move PDF into /hsrp
        run: |
          cp hsrp.pdf ./hsrp.pdf

      - name: Commit PDF back to repository
        uses: stefanweifel/git-auto-commit-action@v5
        with:
          commit_message: "Updated generated hsrp.pdf"
          file_pattern: hsrp.pdf
